apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: mysql-config-volume
        configMap:
          name: flask-mysql-config
      - name: db-data
        persistentVolumeClaim:
          claimName: sql-files-pvc
      containers:
      - name: mysql
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-mysql
              key: db_password
        volumeMounts:
        - name: mysql-config-volume
          mountPath: /etc/mysql/my.cnf
          subPath: my.cnf # this is the file name in the configMap
        - name: db-data
          mountPath: /var/lib/mysql
        ports:
        - containerPort: {{ .Values.sqlContainerPort }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-files-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "standard"

