apiVersion: v1
kind: Service
metadata:
  name: spring-mvc-service
spec:
  # type: NodePort
  type: LoadBalancer
  selector:
    app: spring-mvc-ilia
  ports:
    - name: http
      port: 80 # node port
      targetPort: 8080 # container port
      nodePort: 30001