---
# This playbook removes Apache on all hosts in the inventory file.
- hosts: all
  become: true
  tasks:
  
  - name: Remove apache2 packages
    apt:
      name: apache2
      state: absent
  
  - name: remove PHP Support for Apache2
    apt:
      name: libapache2-mod-php
      state: absent
