---
# This playbook removes Apache on all hosts in the inventory file.
- hosts: all
  become: true
  tasks:
  - name: UnInstall apache2 and PHP packages 
    package: #apt yum (ubuntu/centos)
      name: 
        - '{{ apache }}'
        - '{{ php }}'
      state: absent
      purge: yes

